---
name: ci
'on':
  push:
    paths:
    - ".github/workflows/ci.yml"
    - lib/**
    - "*.gemspec"
    - spec/**
    - Rakefile
    - Gemfile
    - Gemfile.devtools
    - ".rubocop.yml"
  pull_request:
    branches:
    - master
  create: 
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.1'
        - '3.0'
        - '2.7'
        - '2.6'
        - '2.5'
        - jruby
        include:
        - ruby: '3.1'
          coverage: 'true'
        - ruby: 2.7.0
    env:
      COVERAGE: "${{matrix.coverage}}"
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install package dependencies
      run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{matrix.ruby}}"
    - name: Install latest bundler
      run: |
        gem install bundler --no-document
        bundle config set without 'tools benchmarks docs'
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Run all tests
      run: bundle exec rspec
