 
ifeq ($(NIX_TYPE),Linux)
	SED_OPTS = -i
endif

ifeq ($(NIX_TYPE),Darwin)
	SED_OPTS = -i ""
endif


.PHONY: shell
shell: ## access to the system console
	sudo docker-compose run --rm app sh

.PHONY: build
build: ## build the image
	sudo docker-compose build

.PHONY: console
console: ## build the image
	sudo docker-compose run --rm app sh -c "bin/console"

.PHONY: rspec
rspec: ## build the image
	sudo docker-compose run --rm app sh -c "bundle exec rspec"